//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmegaEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OmegaEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to pass at least two values..
        /// </summary>
        public static string AtLeast2Values {
            get {
                return ResourceManager.GetString("AtLeast2Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content archives were already loaded.
        /// </summary>
        public static string ContentArchivesAlreadyLoaded {
            get {
                return ResourceManager.GetString("ContentArchivesAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! All your changes to this file will be lost. Do you wish to continue?.
        /// </summary>
        public static string LoseChangesAsk {
            get {
                return ResourceManager.GetString("LoseChangesAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Min value may not be larger than the Max value..
        /// </summary>
        public static string MinLargerMax {
            get {
                return ResourceManager.GetString("MinLargerMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently no active mod..
        /// </summary>
        public static string NoModActive {
            get {
                return ResourceManager.GetString("NoModActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is not a valid image..
        /// </summary>
        public static string NotAnImage {
            get {
                return ResourceManager.GetString("NotAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game content directory could not be found:.
        /// </summary>
        public static string NotFoundGameContentDir {
            get {
                return ResourceManager.GetString("NotFoundGameContentDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following game content file could not be found:.
        /// </summary>
        public static string NotFoundGameContentFile {
            get {
                return ResourceManager.GetString("NotFoundGameContentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mod directory could not be found:.
        /// </summary>
        public static string NotFoundModContentDir {
            get {
                return ResourceManager.GetString("NotFoundModContentDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no XML data found in the ZIP file..
        /// </summary>
        public static string NoXmlDataInZip {
            get {
                return ResourceManager.GetString("NoXmlDataInZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading &apos;{0}&apos;..
        /// </summary>
        public static string ProblemLoading {
            get {
                return ResourceManager.GetString("ProblemLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string Revert {
            get {
                return ResourceManager.GetString("Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be deleted..
        /// </summary>
        public static string UnableToDelete {
            get {
                return ResourceManager.GetString("UnableToDelete", resourceCulture);
            }
        }
    }
}
