//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerrainSample.World.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerrainSample.World.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The angle-maps size must be equal to the terrain size..
        /// </summary>
        internal static string AngleMapSizeEqualTerrain {
            get {
                return ResourceManager.GetString("AngleMapSizeEqualTerrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calculation has not been completed yet..
        /// </summary>
        internal static string CalculationNotComplete {
            get {
                return ResourceManager.GetString("CalculationNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinates are not within terrain range..
        /// </summary>
        internal static string CoordinatesNotInRange {
            get {
                return ResourceManager.GetString("CoordinatesNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested entry was not found..
        /// </summary>
        internal static string EntryNotFound {
            get {
                return ResourceManager.GetString("EntryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating light angle maps (for shadows).
        /// </summary>
        internal static string GeneratingLingleAngleMaps {
            get {
                return ResourceManager.GetString("GeneratingLingleAngleMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The height-map size must be equal to the terrain size..
        /// </summary>
        internal static string HeightMapSizeEqualTerrain {
            get {
                return ResourceManager.GetString("HeightMapSizeEqualTerrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of this texture map is incorrect..
        /// </summary>
        internal static string InvalidMapSize {
            get {
                return ResourceManager.GetString("InvalidMapSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such entity was found: .
        /// </summary>
        internal static string NoSuchEntity {
            get {
                return ResourceManager.GetString("NoSuchEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is not a valid image..
        /// </summary>
        internal static string NotAnImage {
            get {
                return ResourceManager.GetString("NotAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of {0} was not loaded yet..
        /// </summary>
        internal static string NotLoaded {
            get {
                return ResourceManager.GetString("NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} template is unknown: {1}.
        /// </summary>
        internal static string TemplateUnknown {
            get {
                return ResourceManager.GetString("TemplateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The terrain data was not loaded correctly.
        ///The file is probably damaged..
        /// </summary>
        internal static string TerrainDataNotLoaded {
            get {
                return ResourceManager.GetString("TerrainDataNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The terrain size must be a multiple of three..
        /// </summary>
        internal static string TerrainSizeMultipleOfThree {
            get {
                return ResourceManager.GetString("TerrainSizeMultipleOfThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A color in the texture-map has no according terrain class..
        /// </summary>
        internal static string TerrainTextureColorNotFound {
            get {
                return ResourceManager.GetString("TerrainTextureColorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The texture-map size must be 1/3 of the terrain size..
        /// </summary>
        internal static string TextureMapSizeThirdOfTerrain {
            get {
                return ResourceManager.GetString("TextureMapSizeThirdOfTerrain", resourceCulture);
            }
        }
    }
}
