//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlphaEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes you have made will be saved, so that they will actually become visible..
        /// </summary>
        public static string AutoSavePendingChanges {
            get {
                return ResourceManager.GetString("AutoSavePendingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is not supported by your graphics card..
        /// </summary>
        public static string BadGraphics {
            get {
                return ResourceManager.GetString("BadGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the new language to become effective everywhere, this Mod needs to be closed. Continue?
        ///All open files will be closed. You will be able to save your work first..
        /// </summary>
        public static string CloseModForLangChange {
            get {
                return ResourceManager.GetString("CloseModForLangChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t close Mod
        ///Leave the Mod open and apply the language change only partially for now.
        /// </summary>
        public static string CloseModForLangChangeNo {
            get {
                return ResourceManager.GetString("CloseModForLangChangeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Mod
        ///Close the Mod and apply the language change everywhere.
        /// </summary>
        public static string CloseModForLangChangeYes {
            get {
                return ResourceManager.GetString("CloseModForLangChangeYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CopyCopy {
            get {
                object obj = ResourceManager.GetObject("CopyCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CreateButton {
            get {
                object obj = ResourceManager.GetObject("CreateButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CutButton {
            get {
                object obj = ResourceManager.GetObject("CutButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external data was successfully imported..
        /// </summary>
        public static string DataImported {
            get {
                return ResourceManager.GetString("DataImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DeleteButton {
            get {
                object obj = ResourceManager.GetObject("DeleteButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want delete the {0} checked entries?
        ///Note: This is not necessarily the currently selected one..
        /// </summary>
        public static string DeleteCheckedEntries {
            get {
                return ResourceManager.GetString("DeleteCheckedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want delete the currently selected entry?
        ///{0}.
        /// </summary>
        public static string DeleteSelectedEntry {
            get {
                return ResourceManager.GetString("DeleteSelectedEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory could not be created..
        /// </summary>
        public static string DirectoryNotCreatable {
            get {
                return ResourceManager.GetString("DirectoryNotCreatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected directory is not empty. Use it anyway?.
        /// </summary>
        public static string DirectoryNotEmpty {
            get {
                return ResourceManager.GetString("DirectoryNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel
        ///Choose a different directory.
        /// </summary>
        public static string DirectoryNotEmptyCancel {
            get {
                return ResourceManager.GetString("DirectoryNotEmptyCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue
        ///Use this directory anyway
        ///(not recommended!).
        /// </summary>
        public static string DirectoryNotEmptyContinue {
            get {
                return ResourceManager.GetString("DirectoryNotEmptyContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required version of DirectX is not installed on your computer..
        /// </summary>
        public static string DirectXMissing {
            get {
                return ResourceManager.GetString("DirectXMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DownButton {
            get {
                object obj = ResourceManager.GetObject("DownButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Editor {
            get {
                object obj = ResourceManager.GetObject("Editor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the template..
        /// </summary>
        public static string EnterTemplateName {
            get {
                return ResourceManager.GetString("EnterTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want export the {0} checked entries?
        ///Note: This is not necessarily the currently selected one..
        /// </summary>
        public static string ExportCheckedEntries {
            get {
                return ResourceManager.GetString("ExportCheckedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want export the currently selected entry?
        ///{0}.
        /// </summary>
        public static string ExportSelectedEntry {
            get {
                return ResourceManager.GetString("ExportSelectedEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read game content archives..
        /// </summary>
        public static string FailedReadArchives {
            get {
                return ResourceManager.GetString("FailedReadArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is already open..
        /// </summary>
        public static string FileAlreadyOpen {
            get {
                return ResourceManager.GetString("FileAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is damaged or in an invalid format..
        /// </summary>
        public static string FileDamaged {
            get {
                return ResourceManager.GetString("FileDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file could not be found:.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the file..
        /// </summary>
        public static string FileNotLoadable {
            get {
                return ResourceManager.GetString("FileNotLoadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving the file..
        /// </summary>
        public static string FileNotSavable {
            get {
                return ResourceManager.GetString("FileNotSavable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function isn&apos;t available yet..
        /// </summary>
        public static string FunctionNotAvaialble {
            get {
                return ResourceManager.GetString("FunctionNotAvaialble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game EXE could not be found..
        /// </summary>
        public static string GameEXENotFound {
            get {
                return ResourceManager.GetString("GameEXENotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GoButton {
            get {
                object obj = ResourceManager.GetObject("GoButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImportExportButton {
            get {
                object obj = ResourceManager.GetObject("ImportExportButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Information {
            get {
                object obj = ResourceManager.GetObject("Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory path is invalid..
        /// </summary>
        public static string InvalidDirectoryPath {
            get {
                return ResourceManager.GetString("InvalidDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path is invalid..
        /// </summary>
        public static string InvalidFilePath {
            get {
                return ResourceManager.GetString("InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered data is invalid..
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key was already present in the dictionary..
        /// </summary>
        public static string KeyAlreadyPresent {
            get {
                return ResourceManager.GetString("KeyAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a mod name..
        /// </summary>
        public static string MissingModName {
            get {
                return ResourceManager.GetString("MissingModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a storage location..
        /// </summary>
        public static string MissingStorageLocation {
            get {
                return ResourceManager.GetString("MissingStorageLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mod was successfully packaged into a auto-installable file..
        /// </summary>
        public static string ModPackaged {
            get {
                return ResourceManager.GetString("ModPackaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already in use..
        /// </summary>
        public static string NameInUse {
            get {
                return ResourceManager.GetString("NameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, keep.
        /// </summary>
        public static string NoKeep {
            get {
                return ResourceManager.GetString("NoKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game content directory could not be found..
        /// </summary>
        public static string NotFoundGameContentDir {
            get {
                return ResourceManager.GetString("NotFoundGameContentDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mod directory could not be found..
        /// </summary>
        public static string NotFoundModContentDir {
            get {
                return ResourceManager.GetString("NotFoundModContentDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package file must be created outside of the mod directory..
        /// </summary>
        public static string PackageOutsideMod {
            get {
                return ResourceManager.GetString("PackageOutsideMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dimensions of the oldPartialData and newPartialData arrays must be equal..
        /// </summary>
        public static string PartialDataArrayDimensionsNotEqual {
            get {
                return ResourceManager.GetString("PartialDataArrayDimensionsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PasteButton {
            get {
                object obj = ResourceManager.GetObject("PasteButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RedoButton {
            get {
                object obj = ResourceManager.GetObject("RedoButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RefreshButton {
            get {
                object obj = ResourceManager.GetObject("RefreshButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RenameButton {
            get {
                object obj = ResourceManager.GetObject("RenameButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RunButton {
            get {
                object obj = ResourceManager.GetObject("RunButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SaveButton {
            get {
                object obj = ResourceManager.GetObject("SaveButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes you made?.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Don&apos;t save
        ///Ignore the not saved changes.
        /// </summary>
        public static string SaveChangesNo {
            get {
                return ResourceManager.GetString("SaveChangesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save
        ///Save the file and then close.
        /// </summary>
        public static string SaveChangesYes {
            get {
                return ResourceManager.GetString("SaveChangesYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was saved successfully..
        /// </summary>
        public static string SavedFile {
            get {
                return ResourceManager.GetString("SavedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SearchButton {
            get {
                object obj = ResourceManager.GetObject("SearchButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select {0}:.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will store the current camera perspective as the startup value for this map..
        /// </summary>
        public static string StoreCameraPerspective {
            get {
                return ResourceManager.GetString("StoreCameraPerspective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep previous perspective.
        /// </summary>
        public static string StoreCameraPerspectiveCancel {
            get {
                return ResourceManager.GetString("StoreCameraPerspectiveCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as new startup perspective.
        /// </summary>
        public static string StoreCameraPerspectiveOK {
            get {
                return ResourceManager.GetString("StoreCameraPerspectiveOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template selection.
        /// </summary>
        public static string TemplateSelection {
            get {
                return ResourceManager.GetString("TemplateSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to launch the game using the current Mod.
        ///Please first ensure that you have saved all changes, so that they will actually become visible..
        /// </summary>
        public static string TestInGame {
            get {
                return ResourceManager.GetString("TestInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Continue
        ///Launch the game.
        /// </summary>
        public static string TestInGameContinue {
            get {
                return ResourceManager.GetString("TestInGameContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save and Continue
        ///Save the file and launch the game.
        /// </summary>
        public static string TestInGameContinueSave {
            get {
                return ResourceManager.GetString("TestInGameContinueSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to launch the game and open the current map..
        /// </summary>
        public static string TestInGameMap {
            get {
                return ResourceManager.GetString("TestInGameMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UndoButton {
            get {
                object obj = ResourceManager.GetObject("UndoButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UpButton {
            get {
                object obj = ResourceManager.GetObject("UpButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ValidateButton {
            get {
                object obj = ResourceManager.GetObject("ValidateButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete.
        /// </summary>
        public static string YesDelete {
            get {
                return ResourceManager.GetString("YesDelete", resourceCulture);
            }
        }
    }
}
