<Project>

  <Import Project="$(MSBuildThisFileDirectory)..\Directory.Build.props" />

  <!-- Build config -->
  <PropertyGroup>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <IsPackable>False</IsPackable>
    <DeterministicSourcePaths>False</DeterministicSourcePaths>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="FrameOfReference.UnitTests" />
  </ItemGroup>

  <!-- Remove assets intended for NuGet packaging -->
  <ItemGroup>
    <None Remove="$(MSBuildThisFileDirectory)..\..\*" />
  </ItemGroup>

</Project>
