<Project>

  <!-- Build config -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <IsPackable>False</IsPackable>
    <DeterministicSourcePaths>False</DeterministicSourcePaths>
    <UseMicrosoftTestingPlatformRunner>True</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformCommandLineArguments>$(TestingPlatformCommandLineArguments) --report-xunit-trx --report-xunit-trx-filename $(TargetFramework).trx --results-directory $(MSBuildProjectDirectory)/TestResults</TestingPlatformCommandLineArguments>
  </PropertyGroup>

  <!-- Mark as unit test project -->
  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

  <!-- Remove assets intended for NuGet packaging -->
  <ItemGroup>
    <None Remove="$(MSBuildThisFileDirectory)..\..\*" />
  </ItemGroup>

  <!-- Dependencies -->
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="AwesomeAssertions" Version="9.5.0" />
    <PackageReference Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>

</Project>
