/*
 * Copyright 2006-2014 Bastian Eicher
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/.
 */

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using AlphaFramework.World.Positionables;

namespace AlphaFramework.World.Paths
{
    /// <summary>
    /// Controls how an <see cref="EntityBase{TCoordinates,TTemplate}"/> will move along a path generated by pathfinding.
    /// </summary>
    /// <typeparam name="TCoordinates">Data type for storing position coordinates of objects in the game world.</typeparam>
    /// <seealso cref="EntityBase{TCoordinates,TTemplate}.PathControl"/>
    public class PathControl<TCoordinates> : ICloneable
        where TCoordinates : struct
    {
        /// <summary>
        /// The final target of the pathfinding.
        /// </summary>
        public TCoordinates Target { get; set; }

        private readonly Queue<TCoordinates> _pathNodes = new Queue<TCoordinates>();

        /// <summary>
        /// The path to walk.
        /// </summary>
        /// <remarks>Is not serialized/stored, will be recalculated.</remarks>
        [XmlIgnore]
        public Queue<TCoordinates> PathNodes { get { return _pathNodes; } }

        /// <inheritdoc/>
        public override string ToString()
        {
            return GetType().Name;
        }

        #region Clone
        /// <summary>
        /// Creates a shallow copy of this <see cref="PathControl{TCoordinates}"/>
        /// </summary>
        /// <returns>The cloned <see cref="PathControl{TCoordinates}"/>.</returns>
        public PathControl<TCoordinates> Clone()
        {
            // Perform initial shallow copy
            return (PathControl<TCoordinates>)MemberwiseClone();
        }

        object ICloneable.Clone()
        {
            return Clone();
        }
        #endregion
    }
}
